title: Dhanesh Arole blog
tagline: Some fancy tagline
baseurl: ""

author: 
  name: Dhanesh Arole
  url: https://dhanesharole.github.io

plugins:
  - octopress-paginate

pagination: 
  limit: false
  permalink: /page/:num/
