title: Dhanesh Arole blog
tagline: Some fancy tagline
baseurl: ""

author: 
  name: Dhanesh Arole
  url: https://dhanesharole.github.io

plugins:
  - jekyll-paginate

paginate: 2
paginate_path: /page-:num/